### PR TITLE
Handle non-git projects by resolving promise with empty object

### LINKED ISSUE #58: Crashes on non-git projects
`scm` is unavailable, leading to

```
simpleGit(_this.path).log(function(err, log) {
  var info = log.latest;
```

throwing an error.
Shall we just resolve with an empty response instead in case of `!log`?

### PR DESCRIPTION
**Pull request by duizendnegen**
Fixed #58

### CODE REVIEW

File: lib/scm-data-generators/git.js [hunk 1]
```diff
@@ -14,14 +14,19 @@ module.exports = CoreObject.extend({
...
-        resolve({
-          sha: info.hash.replace("'",''),
-          email: info.author_email.replace("'",''),
-          name: info.author_name,
-          timestamp: new Date(info.date).toISOString(),
-          branch: gitRepoInfo().branch,
-          tag: gitRepoInfo().tag
-        });
+
+        if(!log) {
```
Comment (achambers) [inline lib/scm-data-generators/git.js]: If log does exist then line 16 above will blow up right?

Comment (achambers) [reply lib/scm-data-generators/git.js]: Is this meant to be !info?

**Review by achambers — CHANGES_REQUESTED** [review]
